/* A lexical scanner generated by flex */

/* Scanner skeleton version:
 * $Header: /upc/share/CVS/netcdf-3/ncgen/ncgenyy.c,v 1.15 2009/03/10 22:15:06 russ Exp $
 */

#define FLEX_SCANNER
#define YY_FLEX_MAJOR_VERSION 2
#define YY_FLEX_MINOR_VERSION 5

#include <stdio.h>


/* cfront 1.2 defines "c_plusplus" instead of "__cplusplus" */
#ifdef c_plusplus
#ifndef __cplusplus
#define __cplusplus
#endif
#endif


#ifdef __cplusplus

#include <config.h>
#include <stdlib.h>
#include <unistd.h>

/* Use prototypes in function declarations. */
#define YY_USE_PROTOS

/* The "const" storage-class-modifier is valid. */
#define YY_USE_CONST

#else	/* ! __cplusplus */

#if __STDC__

#define YY_USE_PROTOS
#define YY_USE_CONST

#endif	/* __STDC__ */
#endif	/* ! __cplusplus */

#ifdef __TURBOC__
 #pragma warn -rch
 #pragma warn -use
#include <io.h>
#include <stdlib.h>
#define YY_USE_CONST
#define YY_USE_PROTOS
#endif

#ifdef YY_USE_CONST
#define yyconst const
#else
#define yyconst
#endif


#ifdef YY_USE_PROTOS
#define YY_PROTO(proto) proto
#else
#define YY_PROTO(proto) ()
#endif

/* Returned upon end-of-file. */
#define YY_NULL 0

/* Promotes a possibly negative, possibly signed char to an unsigned
 * integer for use as an array index.  If the signed char is negative,
 * we want to instead treat it as an 8-bit unsigned char, hence the
 * double cast.
 */
#define YY_SC_TO_UI(c) ((unsigned int) (unsigned char) c)

/* Enter a start condition.  This macro really ought to take a parameter,
 * but we do it the disgusting crufty way forced on us by the ()-less
 * definition of BEGIN.
 */
#define BEGIN yy_start = 1 + 2 *

/* Translate the current start state into a value that can be later handed
 * to BEGIN to return to the state.  The YYSTATE alias is for lex
 * compatibility.
 */
#define YY_START ((yy_start - 1) / 2)
#define YYSTATE YY_START

/* Action number for EOF rule of a given start state. */
#define YY_STATE_EOF(state) (YY_END_OF_BUFFER + state + 1)

/* Special action meaning "start processing a new file". */
#define YY_NEW_FILE yyrestart( yyin )

#define YY_END_OF_BUFFER_CHAR 0

/* Size of default input buffer. */
#define YY_BUF_SIZE 16384

typedef struct yy_buffer_state *YY_BUFFER_STATE;

extern int yyleng;
extern FILE *yyin, *yyout;

#define EOB_ACT_CONTINUE_SCAN 0
#define EOB_ACT_END_OF_FILE 1
#define EOB_ACT_LAST_MATCH 2

/* The funky do-while in the following #define is used to turn the definition
 * int a single C statement (which needs a semi-colon terminator).  This
 * avoids problems with code like:
 *
 * 	if ( condition_holds )
 *		yyless( 5 );
 *	else
 *		do_something_else();
 *
 * Prior to using the do-while the compiler would get upset at the
 * "else" because it interpreted the "if" statement as being all
 * done when it reached the ';' after the yyless() call.
 */

/* Return all but the first 'n' matched characters back to the input stream. */

#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		*yy_cp = yy_hold_char; \
		YY_RESTORE_YY_MORE_OFFSET \
		yy_c_buf_p = yy_cp = yy_bp + n - YY_MORE_ADJ; \
		YY_DO_BEFORE_ACTION; /* set up yytext again */ \
		} \
	while ( 0 )

#define unput(c) yyunput( c, yytext_ptr )

/* The following is because we cannot portably get our hands on size_t
 * (without autoconf's help, which isn't available because we want
 * flex-generated scanners to compile on their own).
 */
typedef unsigned int yy_size_t;


struct yy_buffer_state
	{
	FILE *yy_input_file;

	char *yy_ch_buf;		/* input buffer */
	char *yy_buf_pos;		/* current position in input buffer */

	/* Size of input buffer in bytes, not including room for EOB
	 * characters.
	 */
	yy_size_t yy_buf_size;

	/* Number of characters read into yy_ch_buf, not including EOB
	 * characters.
	 */
	int yy_n_chars;

	/* Whether we "own" the buffer - i.e., we know we created it,
	 * and can realloc() it to grow it, and should free() it to
	 * delete it.
	 */
	int yy_is_our_buffer;

	/* Whether this is an "interactive" input source; if so, and
	 * if we're using stdio for input, then we want to use getc()
	 * instead of fread(), to make sure we stop fetching input after
	 * each newline.
	 */
	int yy_is_interactive;

	/* Whether we're considered to be at the beginning of a line.
	 * If so, '^' rules will be active on the next match, otherwise
	 * not.
	 */
	int yy_at_bol;

	/* Whether to try to fill the input buffer when we reach the
	 * end of it.
	 */
	int yy_fill_buffer;

	int yy_buffer_status;
#define YY_BUFFER_NEW 0
#define YY_BUFFER_NORMAL 1
	/* When an EOF's been seen but there's still some text to process
	 * then we mark the buffer as YY_EOF_PENDING, to indicate that we
	 * shouldn't try reading from the input source any more.  We might
	 * still have a bunch of tokens to match, though, because of
	 * possible backing-up.
	 *
	 * When we actually see the EOF, we change the status to "new"
	 * (via yyrestart()), so that the user can continue scanning by
	 * just pointing yyin at a new input file.
	 */
#define YY_BUFFER_EOF_PENDING 2
	};

static YY_BUFFER_STATE yy_current_buffer = 0;

/* We provide macros for accessing buffer states in case in the
 * future we want to put the buffer states in a more general
 * "scanner state".
 */
#define YY_CURRENT_BUFFER yy_current_buffer


/* yy_hold_char holds the character lost when yytext is formed. */
static char yy_hold_char;

static int yy_n_chars;		/* number of characters read into yy_ch_buf */


int yyleng;

/* Points to current character in buffer. */
static char *yy_c_buf_p = (char *) 0;
static int yy_init = 1;		/* whether we need to initialize */
static int yy_start = 0;	/* start state number */

/* Flag which is used to allow yywrap()'s to do buffer switches
 * instead of setting up a fresh yyin.  A bit of a hack ...
 */
static int yy_did_buffer_switch_on_eof;

void yyrestart YY_PROTO(( FILE *input_file ));

void yy_switch_to_buffer YY_PROTO(( YY_BUFFER_STATE new_buffer ));
void yy_load_buffer_state YY_PROTO(( void ));
YY_BUFFER_STATE yy_create_buffer YY_PROTO(( FILE *file, int size ));
void yy_delete_buffer YY_PROTO(( YY_BUFFER_STATE b ));
void yy_init_buffer YY_PROTO(( YY_BUFFER_STATE b, FILE *file ));
void yy_flush_buffer YY_PROTO(( YY_BUFFER_STATE b ));
#define YY_FLUSH_BUFFER yy_flush_buffer( yy_current_buffer )

YY_BUFFER_STATE yy_scan_buffer YY_PROTO(( char *base, yy_size_t size ));
YY_BUFFER_STATE yy_scan_string YY_PROTO(( yyconst char *yy_str ));
YY_BUFFER_STATE yy_scan_bytes YY_PROTO(( yyconst char *bytes, int len ));

static void *yy_flex_alloc YY_PROTO(( yy_size_t ));
static void *yy_flex_realloc YY_PROTO(( void *, yy_size_t ));
static void yy_flex_free YY_PROTO(( void * ));

#define yy_new_buffer yy_create_buffer

#define yy_set_interactive(is_interactive) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_is_interactive = is_interactive; \
	}

#define yy_set_bol(at_bol) \
	{ \
	if ( ! yy_current_buffer ) \
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE ); \
	yy_current_buffer->yy_at_bol = at_bol; \
	}

#define YY_AT_BOL() (yy_current_buffer->yy_at_bol)

typedef unsigned char YY_CHAR;
FILE *yyin = (FILE *) 0, *yyout = (FILE *) 0;
typedef int yy_state_type;
extern char *yytext;
#define yytext_ptr yytext

static yy_state_type yy_get_previous_state YY_PROTO(( void ));
static yy_state_type yy_try_NUL_trans YY_PROTO(( yy_state_type current_state ));
static int yy_get_next_buffer YY_PROTO(( void ));
static void yy_fatal_error YY_PROTO(( yyconst char msg[] ));

/* Done after the current pattern has been matched and before the
 * corresponding action - sets up yytext.
 */
#define YY_DO_BEFORE_ACTION \
	yytext_ptr = yy_bp; \
	yyleng = (int) (yy_cp - yy_bp); \
	yy_hold_char = *yy_cp; \
	*yy_cp = '\0'; \
	yy_c_buf_p = yy_cp;

#define YY_NUM_RULES 30
#define YY_END_OF_BUFFER 31
static yyconst short int yy_accept[264] =
    {   0,
        0,    0,   31,   29,   28,   17,   29,   29,   29,   29,
       19,   29,   22,   22,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   29,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   29,
       29,   29,   28,    0,    2,    0,    0,    0,   19,   22,
       22,    0,    0,   19,   19,    0,   20,    1,   23,   23,
       18,   23,   22,   21,    0,   22,   18,   16,    0,    0,
        0,    0,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,

       16,   16,   16,   16,   16,    0,    0,   24,    0,    0,
        0,    0,    0,   19,    0,    0,   19,    1,   23,   19,
       23,    0,    0,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,    7,   16,   16,   16,   14,   16,   16,
       16,   16,   16,   16,   16,   16,   16,   16,    7,   16,
       16,   16,   16,   16,   16,    0,   27,   25,    0,    0,
       19,    0,   19,   20,   19,    0,    5,    4,   16,   16,
       16,   16,   16,   16,   16,   15,   16,    7,   16,    3,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,   16,   16,   25,    0,   26,    0,   15,    0,   12,

       16,   16,   16,   16,   16,   16,   16,    6,   16,   16,
       16,   16,   16,   16,   16,   16,   16,    0,   16,    8,
       16,   16,   16,   16,   16,   16,   16,   16,   16,   16,
       16,    0,   16,   16,   16,   16,    0,   16,   16,   16,
       16,   16,    0,   16,   16,   13,   13,   16,   16,   16,
       16,   16,   14,   16,    9,   16,   16,   16,   16,   11,
       16,   10,    0
    } ;

static yyconst int yy_ec[256] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    2,    3,
        1,    4,    4,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    5,    6,    7,    6,    6,    6,    6,    8,    6,
        6,    6,    9,    6,   10,   11,   12,   13,   14,   14,
       14,   14,   14,   14,   14,   15,   15,   16,    6,    6,
        6,    6,    6,   17,   18,   19,   20,   21,   22,   23,
       24,   25,   26,   27,   27,   28,   29,   30,   31,   27,
       27,   32,   33,   34,   35,   36,   27,   37,   38,   27,
        6,   39,    6,    6,   27,    6,   40,   41,   42,   43,

       44,   45,   46,   47,   48,   27,   27,   49,   50,   51,
       52,   27,   27,   53,   54,   55,   56,   57,   27,   37,
       58,   27,   59,    6,    6,    6,    1,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   60,   60,   60,   60,   60,   60,   60,   60,   60,
       60,   61,   61,   61,   61,   61,   61,   61,   61,   61,

       61,   61,   61,   61,   61,   61,   61,   61,   61,   61,
       61,   61,   61,   61,    1,    1,    1,    1,    1,    1,
        1,    1,    1,   62,   62,   62,   62,   62,   62,   62,
       62,   62,   62,   62,   62,   62,   62,   62,   62,   63,
       63,   63,   63,   63,   63,   63,   63,    1,    1,    1,
        1,    1,    1,    1,    1
    } ;

static yyconst int yy_meta[64] =
    {   0,
        1,    1,    2,    1,    1,    1,    1,    3,    4,    4,
        4,    1,    5,    5,    5,    1,    4,    5,    5,    5,
        5,    5,    5,    4,    4,    4,    4,    6,    4,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    4,    5,
        5,    5,    5,    5,    5,    4,    4,    4,    6,    4,
        4,    4,    4,    4,    4,    4,    4,    4,    7,    1,
        4,    4,    4
    } ;

static yyconst short int yy_base[274] =
    {   0,
        0,    0,  359, 1375,   62, 1375,   58,  317,   57,   62,
       94,  342,  133,  177,   30,   42,   57,  132,  118,   50,
      172,   63,  146,  167,  175,  183,  180,   72,  193,  200,
      218,  210,  213,  226,  238,  246,  255,  252,  258,  272,
      271,  265,  160,   91, 1375,  309,  298,  122,    0,  127,
        0,  313,  245,    0, 1375,  320, 1375,    0,   46,   72,
      155,  327, 1375, 1375,    0,    0, 1375,  285,  344,  233,
      226,  224,  304,  335,  323,  329,  338,  332,  365,  416,
      350,  371,  380,  401,  386,  411,  421,  436,  427,  441,
      453,  432,  457,  447,  462,  472,  482,  487,  491,  508,

      501,  466,  516,  512,  519,  200,  180, 1375,  217,  297,
      212,  175,  202,  570,  167,  254,  573,    0, 1375,  600,
      571,  141,  137,  568,  573,  585,  578,  613,  603,  594,
      598,  632,  623,  629,  657,  648,  638,  664,  669,  674,
      678,  689,  685,  703,  682,  710,  714,  718,  723,  743,
      748,  739,  730,  755,  759,  107, 1375, 1375,  331,  152,
     1375,  124,  199,  255, 1375,   89,  769,  773,  780,  784,
      787,  790,  794,  799,  820,  824,  827,  830,  837,  833,
      840,  868,  886,  889,  871,  874,  899,  878,  905,  914,
      917,  920,  924, 1375,  137, 1375,  126, 1375,   78, 1375,

      932,  951,  945,  962,  970,  957,  976,  965,  990,  983,
      995, 1003, 1011, 1020, 1015, 1023, 1028,   75, 1049, 1031,
     1061, 1056, 1064, 1074, 1099, 1081, 1069, 1102, 1094, 1112,
     1109,   59, 1115, 1129, 1140, 1147,  248, 1159, 1165, 1154,
     1150, 1175,   52, 1193, 1179,    0,  290, 1186, 1196, 1200,
     1207, 1213, 1375, 1227, 1232, 1248, 1238, 1257, 1263, 1375,
     1266, 1375, 1375, 1329, 1336, 1340, 1346, 1353, 1356,   85,
     1360, 1363, 1368
    } ;

static yyconst short int yy_def[274] =
    {   0,
      263,    1,  263,  263,  263,  263,  264,  265,  263,  263,
      263,  263,  263,  263,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  263,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  263,
      263,  263,  263,  264,  263,  264,  263,  267,   11,   14,
       14,  263,  263,   11,  263,  263,  263,  268,   13,  269,
      269,  269,  263,  263,  270,   14,  263,  266,  263,  263,
      263,  263,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,

      266,  266,  266,  266,  266,  263,  263,  263,  263,  263,
      271,   50,  263,  263,  263,  263,  263,  268,  263,   62,
      270,  263,  263,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  263,  263,  263,  263,  272,
      263,  263,  269,  269,  263,  263,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  263,  263,  263,  263,  263,  263,  263,

      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  263,  266,  266,
      266,  266,  266,  266,  266,  266,  266,  266,  266,  266,
      266,  263,  266,  266,  266,  266,  273,  266,  266,  266,
      266,  266,  263,  266,  266,  273,  273,  266,  266,  266,
      266,  266,  263,  266,  266,  266,  266,  266,  266,  263,
      266,  263,    0,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263
    } ;

static yyconst short int yy_nxt[1439] =
    {   0,
        4,    5,    6,    5,    5,    4,    7,    8,    9,   10,
       11,   12,   13,   14,   14,    4,    4,   15,   16,   17,
       18,   19,   20,   15,   15,   21,   15,   22,   15,   23,
       15,   24,   25,   15,   26,   27,   15,   15,   28,   15,
       29,   30,   31,   19,   32,   15,   15,   33,   34,   15,
       35,   15,   36,   37,   15,   38,   39,   15,    4,    4,
       40,   41,   42,   43,   45,   43,   43,   49,   69,   50,
       51,   51,   49,  119,   50,   51,   51,   81,   52,   73,
       69,   74,  263,   52,   92,   92,   92,   53,   69,  121,
       70,   71,   72,   85,  119,   69,   46,   45,   82,  119,

       52,   69,   70,   71,   72,   52,   54,   54,   54,  253,
       70,   71,   72,  243,   55,   56,   57,   70,   71,   72,
      119,   55,  232,   70,   71,   72,   79,   79,  218,   46,
       80,   80,   80,  196,  110,  110,   55,   56,   57,  112,
      112,  112,   55,   49,  194,   59,   59,   59,   68,   75,
       60,   61,   60,   60,   62,   60,   69,   76,  111,  196,
       63,   43,   77,   43,   43,   64,   92,   86,  198,   65,
       69,  199,   60,   61,   60,   60,   62,   60,   70,   71,
       72,   63,  119,   78,   69,   87,   64,   49,   88,   66,
       66,   66,   70,   71,   72,   67,  166,   91,   52,   89,

       68,   83,  263,  119,   63,   69,   70,   71,   72,   64,
       69,  162,   90,   69,  114,  114,  114,   67,   69,  157,
       52,   69,   84,  263,  157,   63,  119,   70,   71,   72,
       64,   69,   70,   71,   72,   70,   71,   72,   69,  156,
       70,   71,   72,   70,   71,   72,   94,  119,   69,  247,
       93,   69,  247,   70,   71,   72,   69,   95,   98,   92,
       70,   71,   72,   99,   69,   96,  117,  117,  117,   97,
       70,   71,   72,   70,   71,   72,   69,  100,   70,   71,
       72,  101,  119,  123,   69,  122,   70,   71,   72,  102,
       69,  247,   68,   69,  247,  115,   69,  105,   70,   71,

       72,  103,  104,  119,  158,  108,   70,   71,   72,  159,
      159,  263,   70,   71,   72,   70,   71,   72,   70,   71,
       72,  113,  113,   69,  107,  114,  114,  114,  116,  116,
      106,   92,  117,  117,  117,  113,  113,  124,  194,  120,
      120,  120,   69,  195,  195,   70,   71,   72,   68,   68,
       68,   68,  125,   58,  119,   48,  126,  127,  263,   68,
      263,   69,  263,  263,   70,   71,   72,   69,  263,  263,
       69,  263,  128,   69,  263,  119,   69,   80,   80,   80,
      132,  263,   68,   70,   71,   72,  263,  129,   69,   70,
       71,   72,   70,   71,   72,   70,   71,   72,   70,   71,

       72,  263,   68,   69,  263,  263,  263,  263,  263,   69,
       70,   71,   72,  134,  263,  136,  263,  263,   69,  263,
      263,  263,  133,  263,   69,   70,   71,   72,   80,   80,
       80,   70,   71,   72,  263,  263,  130,  263,  131,   69,
       70,   71,   72,  130,  137,  135,   70,   71,   72,   69,
      138,  263,  263,  139,   69,  263,  263,  140,  130,   69,
      131,   70,   71,   72,  130,   69,  263,  263,  141,  263,
       69,   70,   71,   72,   69,  263,   70,   71,   72,   69,
      263,   70,   71,   72,  142,   69,  144,   70,   71,   72,
      263,   69,   70,   71,   72,   69,   70,   71,   72,  263,

       69,   70,   71,   72,   69,  152,  263,   70,   71,   72,
       69,  143,  263,   70,   71,   72,  145,   70,   71,   72,
       69,  146,   70,   71,   72,   69,   70,   71,   72,   69,
      263,  263,   70,   71,   72,  263,  263,  147,  148,   69,
      263,  263,   70,   71,   72,  149,   69,   70,   71,   72,
       69,   70,   71,   72,   69,  151,  263,   69,  150,  263,
      154,   70,   71,   72,  263,  263,  263,  153,   70,   71,
       72,  155,   70,   71,   72,  263,   70,   71,   72,   70,
       71,   72,  114,  114,  114,  117,  117,  117,  263,  167,
      161,  263,   57,   55,  263,   57,  263,  161,  119,  170,

       55,  263,  169,   64,  168,  263,   69,  263,  263,  263,
      263,   69,  161,  263,   57,   55,   69,   57,  161,  119,
      163,   55,  164,   69,   64,  263,  263,  165,   70,   71,
       72,  171,   69,   70,   71,   72,   69,  263,   70,   71,
       72,   69,  163,  172,  164,   70,   71,   72,  165,  173,
      175,   69,  263,  263,   70,   71,   72,  179,   70,   71,
       72,   69,  174,   70,   71,   72,  263,   69,  263,  263,
       69,  178,  263,   70,   71,   72,   69,  263,  263,  263,
      263,  263,  263,   70,   71,   72,   69,  263,  263,   70,
       71,   72,   70,   71,   72,   69,  180,  263,   70,   71,

       72,  176,   69,  182,  177,  181,  263,   69,   70,   71,
       72,  263,   69,  263,  183,  263,   69,   70,   71,   72,
       69,  184,  263,   69,   70,   71,   72,   69,  167,   70,
       71,   72,  263,  263,   70,   71,   72,  263,   70,   71,
       72,   69,   70,   71,   72,   70,   71,   72,   69,   70,
       71,   72,   69,  185,  186,  168,   69,  187,  263,  263,
      263,   69,  263,   70,   71,   72,  188,  189,   69,  263,
       70,   71,   72,  263,   70,   71,   72,   69,   70,   71,
       72,   69,  191,   70,   71,   72,   69,  180,  178,  190,
       70,   71,   72,   69,  263,  200,  263,   69,  263,   70,

       71,   72,  192,   70,   71,   72,  193,   69,   70,   71,
       72,   69,  263,  201,  202,   70,   71,   72,   69,   70,
       71,   72,   69,  263,  263,   69,  263,  180,   69,   70,
       71,   72,   69,   70,   71,   72,  263,   69,  203,  263,
       70,   71,   72,  205,   70,   71,   72,   70,   71,   72,
       70,   71,   72,  204,   70,   71,   72,  207,   69,   70,
       71,   72,   69,  263,  263,   69,  263,  263,   69,  263,
      263,   69,  263,  208,  263,   69,  263,  206,   69,  263,
       70,   71,   72,  263,   70,   71,   72,   70,   71,   72,
       70,   71,   72,   70,   71,   72,  209,   70,   71,   72,

       70,   71,   72,  210,  200,  263,   69,  263,  263,   69,
      263,  263,   69,  263,  263,  263,   69,  263,  263,  263,
      263,  211,  212,  213,   69,  214,  263,   69,   70,   71,
       72,   70,   71,   72,   70,   71,   72,   69,   70,   71,
       72,  263,  263,   69,  263,  263,   70,   71,   72,   70,
       71,   72,   69,  180,  263,   69,  215,  263,   69,   70,
       71,   72,   69,  217,  219,   70,   71,   72,  263,  216,
       69,  208,  220,  263,   70,   71,   72,   70,   71,   72,
       70,   71,   72,   69,   70,   71,   72,  222,  221,   69,
      263,  223,   70,   71,   72,   69,  263,  263,  225,  263,

       69,  227,  263,   69,  224,   70,   71,   72,   69,  263,
      263,   70,   71,   72,   69,  226,  263,   70,   71,   72,
      263,   69,   70,   71,   72,   70,   71,   72,   69,  263,
       70,   71,   72,   69,  263,  263,   70,   71,   72,  263,
      263,   69,  225,   70,   71,   72,  220,  263,  228,   69,
       70,   71,   72,   69,  229,   70,   71,   72,   69,  225,
      263,   69,  263,   70,   71,   72,   69,  263,  231,   69,
      230,   70,   71,   72,  233,   70,   71,   72,  263,  263,
       70,   71,   72,   70,   71,   72,  234,   69,   70,   71,
       72,   70,   71,   72,   69,  178,  239,  263,  263,   69,

      237,  263,   69,  237,  263,  263,  235,   69,  263,   70,
       71,   72,   69,  263,  238,  263,   70,   71,   72,   69,
      263,   70,   71,   72,   70,   71,   72,  263,  236,   70,
       71,   72,   69,  263,   70,   71,   72,   69,  263,  263,
       69,   70,   71,   72,  263,  244,  178,   69,  263,  240,
       69,  263,  263,   69,   70,   71,   72,  242,  263,   70,
       71,   72,   70,   71,   72,  263,  241,   69,  263,   70,
       71,   72,   70,   71,   72,   70,   71,   72,   69,  245,
      248,  263,  263,  263,  176,   69,  249,  263,   69,   70,
       71,   72,   69,  251,  263,  263,  263,   69,  263,  263,

       70,   71,   72,   69,  138,  250,  255,   70,   71,   72,
       70,   71,   72,   69,   70,   71,   72,   69,  252,   70,
       71,   72,  254,  138,   69,   70,   71,   72,  256,  263,
      263,   69,  263,  263,   69,   70,   71,   72,   69,   70,
       71,   72,  263,  263,  263,   69,   70,   71,   72,  255,
      257,   69,  263,   70,   71,   72,   70,   71,   72,  259,
       70,   71,   72,  260,  263,   69,  258,   70,   71,   72,
       69,  263,  260,   70,   71,   72,   69,  263,  262,  263,
      263,  262,  263,  263,  263,  263,   69,   70,   71,   72,
      263,  261,   70,   71,   72,   69,  263,  263,   70,   71,

       72,   69,  263,  263,   69,  263,  263,  263,   70,   71,
       72,  263,  263,  263,  263,  263,  263,   70,   71,   72,
      263,  263,  263,   70,   71,   72,   70,   71,   72,   44,
       44,   44,   44,   44,   44,   44,   47,   47,   47,   47,
       47,   47,   47,   68,   68,   68,  109,  263,  109,  109,
      109,  109,  109,  118,  263,  118,  118,  118,  118,  118,
       60,   60,  160,  263,  160,  197,  263,  197,  246,  246,
      246,  246,  246,  246,    3,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,

      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263
    } ;

static yyconst short int yy_chk[1439] =
    {   0,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    1,    1,    1,    1,    1,    1,    1,
        1,    1,    1,    5,    7,    5,    5,    9,   15,    9,
        9,    9,   10,   59,   10,   10,   10,   20,    9,   16,
       16,   17,   59,   10,   28,   28,   28,   10,   20,  270,
       15,   15,   15,   22,   59,   17,    7,   44,   20,   60,

        9,   22,   16,   16,   16,   10,   11,   11,   11,  243,
       20,   20,   20,  232,   11,   11,   11,   17,   17,   17,
       60,   11,  218,   22,   22,   22,   19,   19,  199,   44,
       19,   19,   19,  197,   48,   48,   11,   11,   11,   50,
       50,   50,   11,   13,  195,   13,   13,   13,  166,   18,
       13,   13,   13,   13,   13,   13,   19,   18,   48,  160,
       13,   43,   18,   43,   43,   13,  156,   23,  162,   13,
       18,  162,   13,   13,   13,   13,   13,   13,   19,   19,
       19,   13,   61,   18,   23,   23,   13,   14,   24,   14,
       14,   14,   18,   18,   18,   14,  123,   27,   14,   25,

      122,   21,  112,   61,   14,   24,   23,   23,   23,   14,
       21,  115,   26,   25,  113,  113,  113,   14,   27,  111,
       14,   26,   21,  112,  109,   14,  163,   24,   24,   24,
       14,   29,   21,   21,   21,   25,   25,   25,   30,  107,
       27,   27,   27,   26,   26,   26,   30,  163,   32,  237,
       29,   33,  237,   29,   29,   29,   31,   31,   32,  106,
       30,   30,   30,   33,   34,   31,  116,  116,  116,   31,
       32,   32,   32,   33,   33,   33,   35,   34,   31,   31,
       31,   35,  164,   72,   36,   71,   34,   34,   34,   36,
       38,  247,   70,   37,  247,   53,   39,   39,   35,   35,

       35,   37,   38,  164,  110,   47,   36,   36,   36,  110,
      110,   46,   38,   38,   38,   37,   37,   37,   39,   39,
       39,   52,   52,   68,   42,   52,   52,   52,   56,   56,
       41,   40,   56,   56,   56,   62,   62,   73,  159,   62,
       62,   62,   73,  159,  159,   68,   68,   68,   69,   69,
       69,   69,   74,   12,   62,    8,   75,   76,    3,   69,
        0,   75,    0,    0,   73,   73,   73,   76,    0,    0,
       78,    0,   77,   74,    0,   62,   77,   79,   79,   79,
       81,    0,   69,   75,   75,   75,    0,   78,   81,   76,
       76,   76,   78,   78,   78,   74,   74,   74,   77,   77,

       77,    0,   69,   79,    0,    0,    0,    0,    0,   82,
       81,   81,   81,   83,    0,   85,    0,    0,   83,    0,
        0,    0,   82,    0,   85,   79,   79,   79,   80,   80,
       80,   82,   82,   82,    0,    0,   80,    0,   80,   84,
       83,   83,   83,   80,   86,   84,   85,   85,   85,   86,
       87,    0,    0,   88,   80,    0,    0,   89,   80,   87,
       80,   84,   84,   84,   80,   89,    0,    0,   90,    0,
       92,   86,   86,   86,   88,    0,   80,   80,   80,   90,
        0,   87,   87,   87,   91,   94,   94,   89,   89,   89,
        0,   91,   92,   92,   92,   93,   88,   88,   88,    0,

       95,   90,   90,   90,  102,  102,    0,   94,   94,   94,
       96,   93,    0,   91,   91,   91,   95,   93,   93,   93,
       97,   96,   95,   95,   95,   98,  102,  102,  102,   99,
        0,    0,   96,   96,   96,    0,    0,   97,   98,  101,
        0,    0,   97,   97,   97,   99,  100,   98,   98,   98,
      104,   99,   99,   99,  103,  101,    0,  105,  100,    0,
      104,  101,  101,  101,    0,    0,    0,  103,  100,  100,
      100,  105,  104,  104,  104,    0,  103,  103,  103,  105,
      105,  105,  114,  114,  114,  117,  117,  117,    0,  124,
      114,    0,  114,  117,    0,  117,    0,  114,  121,  127,

      117,    0,  126,  121,  125,    0,  124,    0,  120,  120,
        0,  125,  114,    0,  114,  117,  127,  117,  114,  121,
      120,  117,  120,  126,  121,    0,    0,  120,  124,  124,
      124,  128,  130,  125,  125,  125,  131,    0,  127,  127,
      127,  129,  120,  129,  120,  126,  126,  126,  120,  132,
      134,  128,    0,    0,  130,  130,  130,  137,  131,  131,
      131,  133,  133,  129,  129,  129,    0,  134,    0,    0,
      132,  136,    0,  128,  128,  128,  137,    0,    0,    0,
        0,    0,    0,  133,  133,  133,  136,    0,    0,  134,
      134,  134,  132,  132,  132,  135,  139,    0,  137,  137,

      137,  135,  138,  141,  135,  140,    0,  139,  136,  136,
      136,    0,  140,    0,  142,    0,  141,  135,  135,  135,
      145,  145,    0,  143,  138,  138,  138,  142,  143,  139,
      139,  139,    0,    0,  140,  140,  140,    0,  141,  141,
      141,  144,  145,  145,  145,  143,  143,  143,  146,  142,
      142,  142,  147,  146,  147,  144,  148,  148,    0,    0,
        0,  149,    0,  144,  144,  144,  149,  151,  153,    0,
      146,  146,  146,    0,  147,  147,  147,  152,  148,  148,
      148,  150,  153,  149,  149,  149,  151,  152,  150,  151,
      153,  153,  153,  154,    0,  169,    0,  155,    0,  152,

      152,  152,  154,  150,  150,  150,  155,  167,  151,  151,
      151,  168,    0,  170,  171,  154,  154,  154,  169,  155,
      155,  155,  170,    0,    0,  171,    0,  173,  172,  167,
      167,  167,  173,  168,  168,  168,    0,  174,  172,    0,
      169,  169,  169,  175,  170,  170,  170,  171,  171,  171,
      172,  172,  172,  174,  173,  173,  173,  179,  175,  174,
      174,  174,  176,    0,    0,  177,    0,    0,  178,    0,
        0,  180,    0,  181,    0,  179,    0,  177,  181,    0,
      175,  175,  175,    0,  176,  176,  176,  177,  177,  177,
      178,  178,  178,  180,  180,  180,  182,  179,  179,  179,

      181,  181,  181,  183,  184,    0,  182,    0,    0,  185,
        0,    0,  186,    0,    0,    0,  188,    0,    0,    0,
        0,  185,  186,  188,  183,  189,    0,  184,  182,  182,
      182,  185,  185,  185,  186,  186,  186,  187,  188,  188,
      188,    0,    0,  189,    0,    0,  183,  183,  183,  184,
      184,  184,  190,  187,    0,  191,  190,    0,  192,  187,
      187,  187,  193,  193,  201,  189,  189,  189,    0,  192,
      201,  191,  202,    0,  190,  190,  190,  191,  191,  191,
      192,  192,  192,  203,  193,  193,  193,  204,  203,  202,
        0,  205,  201,  201,  201,  206,    0,    0,  207,    0,

      204,  210,    0,  208,  206,  203,  203,  203,  205,    0,
        0,  202,  202,  202,  207,  209,    0,  206,  206,  206,
        0,  210,  204,  204,  204,  208,  208,  208,  209,    0,
      205,  205,  205,  211,    0,    0,  207,  207,  207,    0,
        0,  212,  214,  210,  210,  210,  212,    0,  211,  213,
      209,  209,  209,  215,  213,  211,  211,  211,  214,  215,
        0,  216,    0,  212,  212,  212,  217,    0,  217,  220,
      216,  213,  213,  213,  219,  215,  215,  215,    0,    0,
      214,  214,  214,  216,  216,  216,  221,  219,  217,  217,
      217,  220,  220,  220,  222,  223,  227,    0,    0,  221,

      225,    0,  223,  225,    0,    0,  222,  227,    0,  219,
      219,  219,  224,    0,  226,    0,  222,  222,  222,  226,
        0,  221,  221,  221,  223,  223,  223,    0,  224,  227,
      227,  227,  229,    0,  224,  224,  224,  225,    0,    0,
      228,  226,  226,  226,    0,  233,  229,  231,    0,  228,
      230,    0,    0,  233,  229,  229,  229,  231,    0,  225,
      225,  225,  228,  228,  228,    0,  230,  234,    0,  231,
      231,  231,  230,  230,  230,  233,  233,  233,  235,  234,
      238,    0,    0,    0,  235,  236,  239,    0,  241,  234,
      234,  234,  240,  241,    0,    0,    0,  238,    0,    0,

      235,  235,  235,  239,  236,  240,  248,  236,  236,  236,
      241,  241,  241,  242,  240,  240,  240,  245,  242,  238,
      238,  238,  244,  245,  248,  239,  239,  239,  249,    0,
        0,  244,    0,    0,  249,  242,  242,  242,  250,  245,
      245,  245,    0,    0,    0,  251,  248,  248,  248,  251,
      250,  252,    0,  244,  244,  244,  249,  249,  249,  254,
      250,  250,  250,  256,    0,  254,  252,  251,  251,  251,
      255,    0,  258,  252,  252,  252,  257,    0,  259,    0,
        0,  261,    0,    0,    0,    0,  256,  254,  254,  254,
        0,  257,  255,  255,  255,  258,    0,    0,  257,  257,

      257,  259,    0,    0,  261,    0,    0,    0,  256,  256,
      256,    0,    0,    0,    0,    0,    0,  258,  258,  258,
        0,    0,    0,  259,  259,  259,  261,  261,  261,  264,
      264,  264,  264,  264,  264,  264,  265,  265,  265,  265,
      265,  265,  265,  266,  266,  266,  267,    0,  267,  267,
      267,  267,  267,  268,    0,  268,  268,  268,  268,  268,
      269,  269,  271,    0,  271,  272,    0,  272,  273,  273,
      273,  273,  273,  273,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,

      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263,  263,  263,
      263,  263,  263,  263,  263,  263,  263,  263
    } ;

static yy_state_type yy_last_accepting_state;
static char *yy_last_accepting_cpos;

/* The intent behind this definition is that it'll catch
 * any uses of REJECT which flex missed.
 */
#define REJECT reject_used_but_not_detected
#define yymore() yymore_used_but_not_detected
#define YY_MORE_ADJ 0
#define YY_RESTORE_YY_MORE_OFFSET
char *yytext;
#line 1 "ncgen.l"
#define INITIAL 0
#line 2 "ncgen.l"
/*********************************************************************
 *   Copyright 1993, UCAR/Unidata
 *   See netcdf/COPYRIGHT file for copying and redistribution conditions.
 *   $Id: ncgenyy.c,v 1.15 2009/03/10 22:15:06 russ Exp $
 *********************************************************************/

/* Problems:
1. Ideally, we assume the input is true ut8.
   Unfortunately, we may actually get iso-latin-8859-1.
   This means that there will be ambiguity about the characters
   in the range 128-255 because they will look like n-byte unicode
   when they are 1-byte 8859 characters. Because of our encoding,
   8859 characters above 128 will be handles as n-byte utf8 and so
   will probably not lex correctly.
   Solution: assume utf8 and note in the documentation that
   ISO8859 is specifically unsupported.
2. The netcdf function NC_check_name in string.c must be modified to
   conform to the use of UTF8.
3. We actually have three tests for UTF8 of increasing correctness
   (in the sense that the least correct will allow some sequences that
    are technically illegal UTF8).
   The tests are derived from the table at
	    http://www.w3.org/2005/03/23-lex-U
   We include lexical definitions for all three, but use the second version.
*/

/* lex specification for tokens for ncgen */

/* Fill value used by ncdump from version 2.4 and later.  Should match
   definition of FILL_STRING in ../ncdump/vardata.h */
#define FILL_STRING "_"
#define XDR_INT_MIN (-2147483647-1)
#define XDR_INT_MAX 2147483647

char errstr[100];		/* for short error messages */

#include <stdio.h>
#include <string.h>
#include <ctype.h>
#include "genlib.h"
#include "ncgentab.h"

#define YY_BREAK                /* defining as nothing eliminates unreachable
				   statement warnings from flex output, 
                                   but make sure every action ends with
                                   "return" or "break"! */

/* The most correct (validating) version of UTF8 character set
   (Taken from: http://www.w3.org/2005/03/23-lex-U)

The lines of the expression cover the UTF8 characters as follows:
1. non-overlong 2-byte
2. excluding overlongs
3. straight 3-byte
4. excluding surrogates
5. straight 3-byte
6. planes 1-3
7. planes 4-15
8. plane 16

UTF8   ([\xC2-\xDF][\x80-\xBF])                       \
     | (\xE0[\xA0-\xBF][\x80-\xBF])                   \
     | ([\xE1-\xEC][\x80-\xBF][\x80-\xBF])            \
     | (\xED[\x80-\x9F][\x80-\xBF])                   \
     | ([\xEE-\xEF][\x80-\xBF][\x80-\xBF])            \
     | (\xF0[\x90-\xBF][\x80-\xBF][\x80-\xBF])        \
     | ([\xF1-\xF3][\x80-\xBF][\x80-\xBF][\x80-\xBF]) \
     | (\xF4[\x80-\x8F][\x80-\xBF][\x80-\xBF])        \

*/
/* Wish there was some way to ifdef lex files */
/*The most relaxed version of UTF8 (not used)
UTF8 ([\xC0-\xD6].)|([\xE0-\xEF]..)|([\xF0-\xF7]...)
*/
/*The partially relaxed version of UTF8, and the one used here */
/* The old definition of ID
ID ([A-Za-z_]|{UTF8})([A-Z.@#\[\]a-z_0-9+-]|{UTF8})*
*/
/* Don't permit control characters or '/' in names, but other special
   chars OK if escaped.  Note that to preserve backwards
   compatibility, none of the characters _.@+- should be escaped, as
   they were previously permitted in names without escaping.  */
/* New definition to conform to a subset of string.c */
/* Note: this definition of string will work for utf8 as well,
   although it is a very relaxed definition
*/
#line 856 "lex.yy.c"

/* Macros after this point can all be overridden by user definitions in
 * section 1.
 */

#ifndef YY_SKIP_YYWRAP
#ifdef __cplusplus
extern "C" int yywrap YY_PROTO(( void ));
#else
extern int yywrap YY_PROTO(( void ));
#endif
#endif

#ifndef YY_NO_UNPUT
static void yyunput YY_PROTO(( int c, char *buf_ptr ));
#endif

#ifndef yytext_ptr
static void yy_flex_strncpy YY_PROTO(( char *, yyconst char *, int ));
#endif

#ifdef YY_NEED_STRLEN
static int yy_flex_strlen YY_PROTO(( yyconst char * ));
#endif

#ifndef YY_NO_INPUT
#ifdef __cplusplus
static int yyinput YY_PROTO(( void ));
#else
static int input YY_PROTO(( void ));
#endif
#endif

#if YY_STACK_USED
static int yy_start_stack_ptr = 0;
static int yy_start_stack_depth = 0;
static int *yy_start_stack = 0;
#ifndef YY_NO_PUSH_STATE
static void yy_push_state YY_PROTO(( int new_state ));
#endif
#ifndef YY_NO_POP_STATE
static void yy_pop_state YY_PROTO(( void ));
#endif
#ifndef YY_NO_TOP_STATE
static int yy_top_state YY_PROTO(( void ));
#endif

#else
#define YY_NO_PUSH_STATE 1
#define YY_NO_POP_STATE 1
#define YY_NO_TOP_STATE 1
#endif

#ifdef YY_MALLOC_DECL
YY_MALLOC_DECL
#else
#if __STDC__
#ifndef __cplusplus
#include <stdlib.h>
#endif
#else
/* Just try to get by without declaring the routines.  This will fail
 * miserably on non-ANSI systems for which sizeof(size_t) != sizeof(int)
 * or sizeof(void*) != sizeof(int).
 */
#endif
#endif

/* Amount of stuff to slurp up with each read. */
#ifndef YY_READ_BUF_SIZE
#define YY_READ_BUF_SIZE 8192
#endif

/* Copy whatever the last rule matched to the standard output. */

#ifndef ECHO
/* This used to be an fputs(), but since the string might contain NUL's,
 * we now use fwrite().
 */
#define ECHO (void) fwrite( yytext, yyleng, 1, yyout )
#endif

/* Gets input and stuffs it into "buf".  number of characters read, or YY_NULL,
 * is returned in "result".
 */
#ifndef YY_INPUT
#define YY_INPUT(buf,result,max_size) \
	if ( yy_current_buffer->yy_is_interactive ) \
		{ \
		int c = '*', n; \
		for ( n = 0; n < max_size && \
			     (c = getc( yyin )) != EOF && c != '\n'; ++n ) \
			buf[n] = (char) c; \
		if ( c == '\n' ) \
			buf[n++] = (char) c; \
		if ( c == EOF && ferror( yyin ) ) \
			YY_FATAL_ERROR( "input in flex scanner failed" ); \
		result = n; \
		} \
	else if ( ((result = fread( buf, 1, max_size, yyin )) == 0) \
		  && ferror( yyin ) ) \
		YY_FATAL_ERROR( "input in flex scanner failed" );
#endif

/* No semi-colon after return; correct usage is to write "yyterminate();" -
 * we don't want an extra ';' after the "return" because that will cause
 * some compilers to complain about unreachable statements.
 */
#ifndef yyterminate
#define yyterminate() return YY_NULL
#endif

/* Number of entries by which start-condition stack grows. */
#ifndef YY_START_STACK_INCR
#define YY_START_STACK_INCR 25
#endif

/* Report a fatal error. */
#ifndef YY_FATAL_ERROR
#define YY_FATAL_ERROR(msg) yy_fatal_error( msg )
#endif

/* Default declaration of generated scanner - a define so the user can
 * easily add parameters.
 */
#ifndef YY_DECL
#define YY_DECL int yylex YY_PROTO(( void ))
#endif

/* Code executed at the beginning of each rule, after yytext and yyleng
 * have been set up.
 */
#ifndef YY_USER_ACTION
#define YY_USER_ACTION
#endif

/* Code executed at the end of each rule. */
#ifndef YY_BREAK
#define YY_BREAK break;
#endif

#define YY_RULE_SETUP \
	YY_USER_ACTION

YY_DECL
	{
	register yy_state_type yy_current_state;
	register char *yy_cp, *yy_bp;
	register int yy_act;

#line 107 "ncgen.l"

#line 1009 "lex.yy.c"

	if ( yy_init )
		{
		yy_init = 0;

#ifdef YY_USER_INIT
		YY_USER_INIT;
#endif

		if ( ! yy_start )
			yy_start = 1;	/* first start state */

		if ( ! yyin )
			yyin = stdin;

		if ( ! yyout )
			yyout = stdout;

		if ( ! yy_current_buffer )
			yy_current_buffer =
				yy_create_buffer( yyin, YY_BUF_SIZE );

		yy_load_buffer_state();
		}

	while ( 1 )		/* loops until end-of-file is reached */
		{
		yy_cp = yy_c_buf_p;

		/* Support of yytext. */
		*yy_cp = yy_hold_char;

		/* yy_bp points to the position in yy_ch_buf of the start of
		 * the current run.
		 */
		yy_bp = yy_cp;

		yy_current_state = yy_start;
yy_match:
		do
			{
			register YY_CHAR yy_c = yy_ec[YY_SC_TO_UI(*yy_cp)];
			if ( yy_accept[yy_current_state] )
				{
				yy_last_accepting_state = yy_current_state;
				yy_last_accepting_cpos = yy_cp;
				}
			while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
				{
				yy_current_state = (int) yy_def[yy_current_state];
				if ( yy_current_state >= 264 )
					yy_c = yy_meta[(unsigned int) yy_c];
				}
			yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
			++yy_cp;
			}
		while ( yy_base[yy_current_state] != 1375 );

yy_find_action:
		yy_act = yy_accept[yy_current_state];
		if ( yy_act == 0 )
			{ /* have to back up */
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			yy_act = yy_accept[yy_current_state];
			}

		YY_DO_BEFORE_ACTION;


do_action:	/* This label is used only to access EOF actions. */


		switch ( yy_act )
	{ /* beginning of action switch */
			case 0: /* must back up */
			/* undo the effects of YY_DO_BEFORE_ACTION */
			*yy_cp = yy_hold_char;
			yy_cp = yy_last_accepting_cpos;
			yy_current_state = yy_last_accepting_state;
			goto yy_find_action;

case 1:
YY_RULE_SETUP
#line 108 "ncgen.l"
{ /* comment */ 
                          break;
                        }
	YY_BREAK
case 2:
YY_RULE_SETUP
#line 112 "ncgen.l"
{
			 if(yyleng > MAXTRST) {
				yyerror("string too long, truncated\n");
			        yytext[MAXTRST-1] = '\0';
			 }
			 expand_escapes(termstring,(char *)yytext,yyleng);
		 	 return (TERMSTRING);
		        }
	YY_BREAK
case 3:
YY_RULE_SETUP
#line 121 "ncgen.l"
{return (FLOAT_K);}
	YY_BREAK
case 4:
YY_RULE_SETUP
#line 122 "ncgen.l"
{return (CHAR_K);}
	YY_BREAK
case 5:
YY_RULE_SETUP
#line 123 "ncgen.l"
{return (BYTE_K);}
	YY_BREAK
case 6:
YY_RULE_SETUP
#line 124 "ncgen.l"
{return (SHORT_K);}
	YY_BREAK
case 7:
YY_RULE_SETUP
#line 125 "ncgen.l"
{return (INT_K);}
	YY_BREAK
case 8:
YY_RULE_SETUP
#line 126 "ncgen.l"
{return (DOUBLE_K);}
	YY_BREAK
case 9:
YY_RULE_SETUP
#line 127 "ncgen.l"
{int_val = -1;
			 return (NC_UNLIMITED_K);}
	YY_BREAK
case 10:
YY_RULE_SETUP
#line 130 "ncgen.l"
{return (DIMENSIONS);}
	YY_BREAK
case 11:
YY_RULE_SETUP
#line 131 "ncgen.l"
{return (VARIABLES);}
	YY_BREAK
case 12:
YY_RULE_SETUP
#line 132 "ncgen.l"
{return (DATA);}
	YY_BREAK
case 13:
YY_RULE_SETUP
#line 133 "ncgen.l"
{
		char *s = (char*)yytext+strlen("netcdf");
		char *t = (char*)yytext+yyleng-1;
		while (isspace(*s))
			s++;
		while (isspace(*t))
			t--;
		t++;
                if (t-s+1 < 1) {
                        yyerror("netCDF name required");
                        return (DATA); /* generate syntax error */
                }
		netcdfname = (char *) emalloc(t-s+1);
		(void) strncpy(netcdfname, s, t-s);
		netcdfname[t-s] = '\0';
		deescapify(netcdfname);  /* so "\5foo" becomes "5foo", for example */
		return (NETCDF);
		}
	YY_BREAK
case 14:
YY_RULE_SETUP
#line 151 "ncgen.l"
{ /* missing value (pre-2.4 backward compatibility) */
                if (yytext[0] == '-') {
		    double_val = -NC_FILL_DOUBLE;
                } else {
		    double_val = NC_FILL_DOUBLE;
                }
		return (DOUBLE_CONST);
		}
	YY_BREAK
case 15:
YY_RULE_SETUP
#line 159 "ncgen.l"
{ /* missing value (pre-2.4 backward compatibility) */
                if (yytext[0] == '-') {
		    float_val = -NC_FILL_FLOAT;
                } else {
		    float_val = NC_FILL_FLOAT;
                }
		return (FLOAT_CONST);
		}
	YY_BREAK
case 16:
YY_RULE_SETUP
#line 167 "ncgen.l"
{
                if (STREQ((char *)yytext, FILL_STRING))
		        return (FILLVALUE);
		if ((yylval = lookup((char *)yytext)) == NULL) {
			yylval = install((char *)yytext);
			}
		return (IDENT);
		}
	YY_BREAK
case 17:
YY_RULE_SETUP
#line 176 "ncgen.l"
{
		lineno++ ;
                break;
		}
	YY_BREAK
case 18:
YY_RULE_SETUP
#line 181 "ncgen.l"
{
                int ii;
		if (sscanf((char*)yytext, "%d", &ii) != 1) {
		    sprintf(errstr,"bad byte constant: %s",(char*)yytext);
		    yyerror(errstr);
		}
                byte_val = ii;
		if (ii != (int)byte_val) {
		    sprintf(errstr,"byte constant out of range (-128,127): %s",(char*)yytext);
		    yyerror(errstr);
		}
		return (BYTE_CONST);
                }
	YY_BREAK
case 19:
YY_RULE_SETUP
#line 195 "ncgen.l"
{
		if (sscanf((char*)yytext, "%le", &double_val) != 1) {
		    sprintf(errstr,"bad long or double constant: %s",(char*)yytext);
		    yyerror(errstr);
		}
                return (DOUBLE_CONST);
                }
	YY_BREAK
case 20:
YY_RULE_SETUP
#line 202 "ncgen.l"
{
		if (sscanf((char*)yytext, "%e", &float_val) != 1) {
		    sprintf(errstr,"bad float constant: %s",(char*)yytext);
		    yyerror(errstr);
		}
                return (FLOAT_CONST);
                }
	YY_BREAK
case 21:
YY_RULE_SETUP
#line 209 "ncgen.l"
{
		if (sscanf((char*)yytext, "%hd", &short_val) != 1) {
		    sprintf(errstr,"bad short constant: %s",(char*)yytext);
		    yyerror(errstr);
		}
		return (SHORT_CONST);
	        }
	YY_BREAK
case 22:
YY_RULE_SETUP
#line 216 "ncgen.l"
{
    		char *ptr;
                errno = 0;
		double_val = strtod((char*)yytext, &ptr);
		if (errno != 0 && double_val == 0.0) {
		    sprintf(errstr,"bad numerical constant: %s",(char*)yytext);
		    yyerror(errstr);
		}
                if (double_val < XDR_INT_MIN ||double_val > XDR_INT_MAX) {
                    return DOUBLE_CONST;
                } else {
                    int_val = (int) double_val;
                    return INT_CONST;
                }
	        }
	YY_BREAK
case 23:
YY_RULE_SETUP
#line 231 "ncgen.l"
{
    		char *ptr;
                long long_val;
                errno = 0;
		long_val = strtol((char*)yytext, &ptr, 0);
		if (errno != 0) {
		    sprintf(errstr,"bad long constant: %s",(char*)yytext);
		    yyerror(errstr);
		}
                if (long_val < XDR_INT_MIN || long_val > XDR_INT_MAX) {
                    double_val = (double) long_val;
                    return DOUBLE_CONST;
                } else {
                    int_val = (int) long_val;
                    return INT_CONST;
                }
	        }
	YY_BREAK
case 24:
YY_RULE_SETUP
#line 248 "ncgen.l"
{
	        (void) sscanf((char*)&yytext[1],"%c",&byte_val);
		return (BYTE_CONST);
                }
	YY_BREAK
case 25:
YY_RULE_SETUP
#line 252 "ncgen.l"
{
		byte_val = (char) strtol((char*)&yytext[2], (char **) 0, 8);
		return (BYTE_CONST);
                }
	YY_BREAK
case 26:
YY_RULE_SETUP
#line 256 "ncgen.l"
{
		byte_val = (char) strtol((char*)&yytext[3], (char **) 0, 16);
		return (BYTE_CONST);
                }
	YY_BREAK
case 27:
YY_RULE_SETUP
#line 260 "ncgen.l"
{
	       switch ((char)yytext[2]) {
	          case 'a': byte_val = '\007'; break; /* not everyone under-
						       * stands '\a' yet */
     	          case 'b': byte_val = '\b'; break;
		  case 'f': byte_val = '\f'; break;
		  case 'n': byte_val = '\n'; break;
		  case 'r': byte_val = '\r'; break;
		  case 't': byte_val = '\t'; break;
		  case 'v': byte_val = '\v'; break;
		  case '\\': byte_val = '\\'; break;
		  case '?': byte_val = '\177'; break;
		  case '\'': byte_val = '\''; break;
		  default: byte_val = (char)yytext[2];
	           }
		return (BYTE_CONST);
                }
	YY_BREAK
case 28:
YY_RULE_SETUP
#line 278 "ncgen.l"
{ /* whitespace */ 
		  break;        
		}
	YY_BREAK
case 29:
YY_RULE_SETUP
#line 281 "ncgen.l"
{/* Note: this next rule will not work for UTF8 characters */
		return (yytext[0]) ;
		}
	YY_BREAK
case 30:
YY_RULE_SETUP
#line 285 "ncgen.l"
ECHO;
	YY_BREAK
#line 1382 "lex.yy.c"
case YY_STATE_EOF(INITIAL):
	yyterminate();

	case YY_END_OF_BUFFER:
		{
		/* Amount of text matched not including the EOB char. */
		int yy_amount_of_matched_text = (int) (yy_cp - yytext_ptr) - 1;

		/* Undo the effects of YY_DO_BEFORE_ACTION. */
		*yy_cp = yy_hold_char;
		YY_RESTORE_YY_MORE_OFFSET

		if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_NEW )
			{
			/* We're scanning a new file or input source.  It's
			 * possible that this happened because the user
			 * just pointed yyin at a new source and called
			 * yylex().  If so, then we have to assure
			 * consistency between yy_current_buffer and our
			 * globals.  Here is the right place to do so, because
			 * this is the first action (other than possibly a
			 * back-up) that will match for the new input source.
			 */
			yy_n_chars = yy_current_buffer->yy_n_chars;
			yy_current_buffer->yy_input_file = yyin;
			yy_current_buffer->yy_buffer_status = YY_BUFFER_NORMAL;
			}

		/* Note that here we test for yy_c_buf_p "<=" to the position
		 * of the first EOB in the buffer, since yy_c_buf_p will
		 * already have been incremented past the NUL character
		 * (since all states make transitions on EOB to the
		 * end-of-buffer state).  Contrast this with the test
		 * in input().
		 */
		if ( yy_c_buf_p <= &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			{ /* This was really a NUL. */
			yy_state_type yy_next_state;

			yy_c_buf_p = yytext_ptr + yy_amount_of_matched_text;

			yy_current_state = yy_get_previous_state();

			/* Okay, we're now positioned to make the NUL
			 * transition.  We couldn't have
			 * yy_get_previous_state() go ahead and do it
			 * for us because it doesn't know how to deal
			 * with the possibility of jamming (and we don't
			 * want to build jamming into it because then it
			 * will run more slowly).
			 */

			yy_next_state = yy_try_NUL_trans( yy_current_state );

			yy_bp = yytext_ptr + YY_MORE_ADJ;

			if ( yy_next_state )
				{
				/* Consume the NUL. */
				yy_cp = ++yy_c_buf_p;
				yy_current_state = yy_next_state;
				goto yy_match;
				}

			else
				{
				yy_cp = yy_c_buf_p;
				goto yy_find_action;
				}
			}

		else switch ( yy_get_next_buffer() )
			{
			case EOB_ACT_END_OF_FILE:
				{
				yy_did_buffer_switch_on_eof = 0;

				if ( yywrap() )
					{
					/* Note: because we've taken care in
					 * yy_get_next_buffer() to have set up
					 * yytext, we can now set up
					 * yy_c_buf_p so that if some total
					 * hoser (like flex itself) wants to
					 * call the scanner after we return the
					 * YY_NULL, it'll still work - another
					 * YY_NULL will get returned.
					 */
					yy_c_buf_p = yytext_ptr + YY_MORE_ADJ;

					yy_act = YY_STATE_EOF(YY_START);
					goto do_action;
					}

				else
					{
					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
					}
				break;
				}

			case EOB_ACT_CONTINUE_SCAN:
				yy_c_buf_p =
					yytext_ptr + yy_amount_of_matched_text;

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_match;

			case EOB_ACT_LAST_MATCH:
				yy_c_buf_p =
				&yy_current_buffer->yy_ch_buf[yy_n_chars];

				yy_current_state = yy_get_previous_state();

				yy_cp = yy_c_buf_p;
				yy_bp = yytext_ptr + YY_MORE_ADJ;
				goto yy_find_action;
			}
		break;
		}

	default:
		YY_FATAL_ERROR(
			"fatal flex scanner internal error--no action found" );
	} /* end of action switch */
		} /* end of scanning one token */
	} /* end of yylex */


/* yy_get_next_buffer - try to read in a new buffer
 *
 * Returns a code representing an action:
 *	EOB_ACT_LAST_MATCH -
 *	EOB_ACT_CONTINUE_SCAN - continue scanning from current position
 *	EOB_ACT_END_OF_FILE - end of file
 */

static int yy_get_next_buffer()
	{
	register char *dest = yy_current_buffer->yy_ch_buf;
	register char *source = yytext_ptr;
	register int number_to_move, i;
	int ret_val;

	if ( yy_c_buf_p > &yy_current_buffer->yy_ch_buf[yy_n_chars + 1] )
		YY_FATAL_ERROR(
		"fatal flex scanner internal error--end of buffer missed" );

	if ( yy_current_buffer->yy_fill_buffer == 0 )
		{ /* Don't try to fill the buffer, so this is an EOF. */
		if ( yy_c_buf_p - yytext_ptr - YY_MORE_ADJ == 1 )
			{
			/* We matched a single character, the EOB, so
			 * treat this as a final EOF.
			 */
			return EOB_ACT_END_OF_FILE;
			}

		else
			{
			/* We matched some text prior to the EOB, first
			 * process it.
			 */
			return EOB_ACT_LAST_MATCH;
			}
		}

	/* Try to read more data. */

	/* First move last chars to start of buffer. */
	number_to_move = (int) (yy_c_buf_p - yytext_ptr) - 1;

	for ( i = 0; i < number_to_move; ++i )
		*(dest++) = *(source++);

	if ( yy_current_buffer->yy_buffer_status == YY_BUFFER_EOF_PENDING )
		/* don't do the read, it's not guaranteed to return an EOF,
		 * just force an EOF
		 */
		yy_current_buffer->yy_n_chars = yy_n_chars = 0;

	else
		{
		int num_to_read =
			yy_current_buffer->yy_buf_size - number_to_move - 1;

		while ( num_to_read <= 0 )
			{ /* Not enough room in the buffer - grow it. */
#ifdef YY_USES_REJECT
			YY_FATAL_ERROR(
"input buffer overflow, can't enlarge buffer because scanner uses REJECT" );
#else

			/* just a shorter name for the current buffer */
			YY_BUFFER_STATE b = yy_current_buffer;

			int yy_c_buf_p_offset =
				(int) (yy_c_buf_p - b->yy_ch_buf);

			if ( b->yy_is_our_buffer )
				{
				int new_size = b->yy_buf_size * 2;

				if ( new_size <= 0 )
					b->yy_buf_size += b->yy_buf_size / 8;
				else
					b->yy_buf_size *= 2;

				b->yy_ch_buf = (char *)
					/* Include room in for 2 EOB chars. */
					yy_flex_realloc( (void *) b->yy_ch_buf,
							 b->yy_buf_size + 2 );
				}
			else
				/* Can't grow it, we don't own it. */
				b->yy_ch_buf = 0;

			if ( ! b->yy_ch_buf )
				YY_FATAL_ERROR(
				"fatal error - scanner input buffer overflow" );

			yy_c_buf_p = &b->yy_ch_buf[yy_c_buf_p_offset];

			num_to_read = yy_current_buffer->yy_buf_size -
						number_to_move - 1;
#endif
			}

		if ( num_to_read > YY_READ_BUF_SIZE )
			num_to_read = YY_READ_BUF_SIZE;

		/* Read in more data. */
		YY_INPUT( (&yy_current_buffer->yy_ch_buf[number_to_move]),
			yy_n_chars, num_to_read );

		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	if ( yy_n_chars == 0 )
		{
		if ( number_to_move == YY_MORE_ADJ )
			{
			ret_val = EOB_ACT_END_OF_FILE;
			yyrestart( yyin );
			}

		else
			{
			ret_val = EOB_ACT_LAST_MATCH;
			yy_current_buffer->yy_buffer_status =
				YY_BUFFER_EOF_PENDING;
			}
		}

	else
		ret_val = EOB_ACT_CONTINUE_SCAN;

	yy_n_chars += number_to_move;
	yy_current_buffer->yy_ch_buf[yy_n_chars] = YY_END_OF_BUFFER_CHAR;
	yy_current_buffer->yy_ch_buf[yy_n_chars + 1] = YY_END_OF_BUFFER_CHAR;

	yytext_ptr = &yy_current_buffer->yy_ch_buf[0];

	return ret_val;
	}


/* yy_get_previous_state - get the state just before the EOB char was reached */

static yy_state_type yy_get_previous_state()
	{
	register yy_state_type yy_current_state;
	register char *yy_cp;

	yy_current_state = yy_start;

	for ( yy_cp = yytext_ptr + YY_MORE_ADJ; yy_cp < yy_c_buf_p; ++yy_cp )
		{
		register YY_CHAR yy_c = (*yy_cp ? yy_ec[YY_SC_TO_UI(*yy_cp)] : 1);
		if ( yy_accept[yy_current_state] )
			{
			yy_last_accepting_state = yy_current_state;
			yy_last_accepting_cpos = yy_cp;
			}
		while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
			{
			yy_current_state = (int) yy_def[yy_current_state];
			if ( yy_current_state >= 264 )
				yy_c = yy_meta[(unsigned int) yy_c];
			}
		yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
		}

	return yy_current_state;
	}


/* yy_try_NUL_trans - try to make a transition on the NUL character
 *
 * synopsis
 *	next_state = yy_try_NUL_trans( current_state );
 */

#ifdef YY_USE_PROTOS
static yy_state_type yy_try_NUL_trans( yy_state_type yy_current_state )
#else
static yy_state_type yy_try_NUL_trans( yy_current_state )
yy_state_type yy_current_state;
#endif
	{
	register int yy_is_jam;
	register char *yy_cp = yy_c_buf_p;

	register YY_CHAR yy_c = 1;
	if ( yy_accept[yy_current_state] )
		{
		yy_last_accepting_state = yy_current_state;
		yy_last_accepting_cpos = yy_cp;
		}
	while ( yy_chk[yy_base[yy_current_state] + yy_c] != yy_current_state )
		{
		yy_current_state = (int) yy_def[yy_current_state];
		if ( yy_current_state >= 264 )
			yy_c = yy_meta[(unsigned int) yy_c];
		}
	yy_current_state = yy_nxt[yy_base[yy_current_state] + (unsigned int) yy_c];
	yy_is_jam = (yy_current_state == 263);

	return yy_is_jam ? 0 : yy_current_state;
	}


#ifndef YY_NO_UNPUT
#ifdef YY_USE_PROTOS
static void yyunput( int c, register char *yy_bp )
#else
static void yyunput( c, yy_bp )
int c;
register char *yy_bp;
#endif
	{
	register char *yy_cp = yy_c_buf_p;

	/* undo effects of setting up yytext */
	*yy_cp = yy_hold_char;

	if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
		{ /* need to shift things up to make room */
		/* +2 for EOB chars. */
		register int number_to_move = yy_n_chars + 2;
		register char *dest = &yy_current_buffer->yy_ch_buf[
					yy_current_buffer->yy_buf_size + 2];
		register char *source =
				&yy_current_buffer->yy_ch_buf[number_to_move];

		while ( source > yy_current_buffer->yy_ch_buf )
			*--dest = *--source;

		yy_cp += (int) (dest - source);
		yy_bp += (int) (dest - source);
		yy_current_buffer->yy_n_chars =
			yy_n_chars = yy_current_buffer->yy_buf_size;

		if ( yy_cp < yy_current_buffer->yy_ch_buf + 2 )
			YY_FATAL_ERROR( "flex scanner push-back overflow" );
		}

	*--yy_cp = (char) c;


	yytext_ptr = yy_bp;
	yy_hold_char = *yy_cp;
	yy_c_buf_p = yy_cp;
	}
#endif	/* ifndef YY_NO_UNPUT */


#ifdef __cplusplus
static int yyinput()
#else
static int input()
#endif
	{
	int c;

	*yy_c_buf_p = yy_hold_char;

	if ( *yy_c_buf_p == YY_END_OF_BUFFER_CHAR )
		{
		/* yy_c_buf_p now points to the character we want to return.
		 * If this occurs *before* the EOB characters, then it's a
		 * valid NUL; if not, then we've hit the end of the buffer.
		 */
		if ( yy_c_buf_p < &yy_current_buffer->yy_ch_buf[yy_n_chars] )
			/* This was really a NUL. */
			*yy_c_buf_p = '\0';

		else
			{ /* need more input */
			int offset = yy_c_buf_p - yytext_ptr;
			++yy_c_buf_p;

			switch ( yy_get_next_buffer() )
				{
				case EOB_ACT_LAST_MATCH:
					/* This happens because yy_g_n_b()
					 * sees that we've accumulated a
					 * token and flags that we need to
					 * try matching the token before
					 * proceeding.  But for input(),
					 * there's no matching to consider.
					 * So convert the EOB_ACT_LAST_MATCH
					 * to EOB_ACT_END_OF_FILE.
					 */

					/* Reset buffer status. */
					yyrestart( yyin );

					/* fall through */

				case EOB_ACT_END_OF_FILE:
					{
					if ( yywrap() )
						return EOF;

					if ( ! yy_did_buffer_switch_on_eof )
						YY_NEW_FILE;
#ifdef __cplusplus
					return yyinput();
#else
					return input();
#endif
					}

				case EOB_ACT_CONTINUE_SCAN:
					yy_c_buf_p = yytext_ptr + offset;
					break;
				}
			}
		}

	c = *(unsigned char *) yy_c_buf_p;	/* cast for 8-bit char's */
	*yy_c_buf_p = '\0';	/* preserve yytext */
	yy_hold_char = *++yy_c_buf_p;


	return c;
	}


#ifdef YY_USE_PROTOS
void yyrestart( FILE *input_file )
#else
void yyrestart( input_file )
FILE *input_file;
#endif
	{
	if ( ! yy_current_buffer )
		yy_current_buffer = yy_create_buffer( yyin, YY_BUF_SIZE );

	yy_init_buffer( yy_current_buffer, input_file );
	yy_load_buffer_state();
	}


#ifdef YY_USE_PROTOS
void yy_switch_to_buffer( YY_BUFFER_STATE new_buffer )
#else
void yy_switch_to_buffer( new_buffer )
YY_BUFFER_STATE new_buffer;
#endif
	{
	if ( yy_current_buffer == new_buffer )
		return;

	if ( yy_current_buffer )
		{
		/* Flush out information for old buffer. */
		*yy_c_buf_p = yy_hold_char;
		yy_current_buffer->yy_buf_pos = yy_c_buf_p;
		yy_current_buffer->yy_n_chars = yy_n_chars;
		}

	yy_current_buffer = new_buffer;
	yy_load_buffer_state();

	/* We don't actually know whether we did this switch during
	 * EOF (yywrap()) processing, but the only time this flag
	 * is looked at is after yywrap() is called, so it's safe
	 * to go ahead and always set it.
	 */
	yy_did_buffer_switch_on_eof = 1;
	}


#ifdef YY_USE_PROTOS
void yy_load_buffer_state( void )
#else
void yy_load_buffer_state()
#endif
	{
	yy_n_chars = yy_current_buffer->yy_n_chars;
	yytext_ptr = yy_c_buf_p = yy_current_buffer->yy_buf_pos;
	yyin = yy_current_buffer->yy_input_file;
	yy_hold_char = *yy_c_buf_p;
	}


#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_create_buffer( FILE *file, int size )
#else
YY_BUFFER_STATE yy_create_buffer( file, size )
FILE *file;
int size;
#endif
	{
	YY_BUFFER_STATE b;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_buf_size = size;

	/* yy_ch_buf has to be 2 characters longer than the size given because
	 * we need to put in 2 end-of-buffer characters.
	 */
	b->yy_ch_buf = (char *) yy_flex_alloc( b->yy_buf_size + 2 );
	if ( ! b->yy_ch_buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_create_buffer()" );

	b->yy_is_our_buffer = 1;

	yy_init_buffer( b, file );

	return b;
	}


#ifdef YY_USE_PROTOS
void yy_delete_buffer( YY_BUFFER_STATE b )
#else
void yy_delete_buffer( b )
YY_BUFFER_STATE b;
#endif
	{
	if ( ! b )
		return;

	if ( b == yy_current_buffer )
		yy_current_buffer = (YY_BUFFER_STATE) 0;

	if ( b->yy_is_our_buffer )
		yy_flex_free( (void *) b->yy_ch_buf );

	yy_flex_free( (void *) b );
	}


#ifndef YY_ALWAYS_INTERACTIVE
#ifndef YY_NEVER_INTERACTIVE
extern int isatty YY_PROTO(( int ));
#endif
#endif

#ifdef YY_USE_PROTOS
void yy_init_buffer( YY_BUFFER_STATE b, FILE *file )
#else
void yy_init_buffer( b, file )
YY_BUFFER_STATE b;
FILE *file;
#endif


	{
	yy_flush_buffer( b );

	b->yy_input_file = file;
	b->yy_fill_buffer = 1;

#if YY_ALWAYS_INTERACTIVE
	b->yy_is_interactive = 1;
#else
#if YY_NEVER_INTERACTIVE
	b->yy_is_interactive = 0;
#else
	b->yy_is_interactive = file ? (isatty( fileno(file) ) > 0) : 0;
#endif
#endif
	}


#ifdef YY_USE_PROTOS
void yy_flush_buffer( YY_BUFFER_STATE b )
#else
void yy_flush_buffer( b )
YY_BUFFER_STATE b;
#endif

	{
	if ( ! b )
		return;

	b->yy_n_chars = 0;

	/* We always need two end-of-buffer characters.  The first causes
	 * a transition to the end-of-buffer state.  The second causes
	 * a jam in that state.
	 */
	b->yy_ch_buf[0] = YY_END_OF_BUFFER_CHAR;
	b->yy_ch_buf[1] = YY_END_OF_BUFFER_CHAR;

	b->yy_buf_pos = &b->yy_ch_buf[0];

	b->yy_at_bol = 1;
	b->yy_buffer_status = YY_BUFFER_NEW;

	if ( b == yy_current_buffer )
		yy_load_buffer_state();
	}


#ifndef YY_NO_SCAN_BUFFER
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_buffer( char *base, yy_size_t size )
#else
YY_BUFFER_STATE yy_scan_buffer( base, size )
char *base;
yy_size_t size;
#endif
	{
	YY_BUFFER_STATE b;

	if ( size < 2 ||
	     base[size-2] != YY_END_OF_BUFFER_CHAR ||
	     base[size-1] != YY_END_OF_BUFFER_CHAR )
		/* They forgot to leave room for the EOB's. */
		return 0;

	b = (YY_BUFFER_STATE) yy_flex_alloc( sizeof( struct yy_buffer_state ) );
	if ( ! b )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_buffer()" );

	b->yy_buf_size = size - 2;	/* "- 2" to take care of EOB's */
	b->yy_buf_pos = b->yy_ch_buf = base;
	b->yy_is_our_buffer = 0;
	b->yy_input_file = 0;
	b->yy_n_chars = b->yy_buf_size;
	b->yy_is_interactive = 0;
	b->yy_at_bol = 1;
	b->yy_fill_buffer = 0;
	b->yy_buffer_status = YY_BUFFER_NEW;

	yy_switch_to_buffer( b );

	return b;
	}
#endif


#ifndef YY_NO_SCAN_STRING
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_string( yyconst char *yy_str )
#else
YY_BUFFER_STATE yy_scan_string( yy_str )
yyconst char *yy_str;
#endif
	{
	int len;
	for ( len = 0; yy_str[len]; ++len )
		;

	return yy_scan_bytes( yy_str, len );
	}
#endif


#ifndef YY_NO_SCAN_BYTES
#ifdef YY_USE_PROTOS
YY_BUFFER_STATE yy_scan_bytes( yyconst char *bytes, int len )
#else
YY_BUFFER_STATE yy_scan_bytes( bytes, len )
yyconst char *bytes;
int len;
#endif
	{
	YY_BUFFER_STATE b;
	char *buf;
	yy_size_t n;
	int i;

	/* Get memory for full buffer, including space for trailing EOB's. */
	n = len + 2;
	buf = (char *) yy_flex_alloc( n );
	if ( ! buf )
		YY_FATAL_ERROR( "out of dynamic memory in yy_scan_bytes()" );

	for ( i = 0; i < len; ++i )
		buf[i] = bytes[i];

	buf[len] = buf[len+1] = YY_END_OF_BUFFER_CHAR;

	b = yy_scan_buffer( buf, n );
	if ( ! b )
		YY_FATAL_ERROR( "bad buffer in yy_scan_bytes()" );

	/* It's okay to grow etc. this buffer, and we should throw it
	 * away when we're done.
	 */
	b->yy_is_our_buffer = 1;

	return b;
	}
#endif


#ifndef YY_NO_PUSH_STATE
#ifdef YY_USE_PROTOS
static void yy_push_state( int new_state )
#else
static void yy_push_state( new_state )
int new_state;
#endif
	{
	if ( yy_start_stack_ptr >= yy_start_stack_depth )
		{
		yy_size_t new_size;

		yy_start_stack_depth += YY_START_STACK_INCR;
		new_size = yy_start_stack_depth * sizeof( int );

		if ( ! yy_start_stack )
			yy_start_stack = (int *) yy_flex_alloc( new_size );

		else
			yy_start_stack = (int *) yy_flex_realloc(
					(void *) yy_start_stack, new_size );

		if ( ! yy_start_stack )
			YY_FATAL_ERROR(
			"out of memory expanding start-condition stack" );
		}

	yy_start_stack[yy_start_stack_ptr++] = YY_START;

	BEGIN(new_state);
	}
#endif


#ifndef YY_NO_POP_STATE
static void yy_pop_state()
	{
	if ( --yy_start_stack_ptr < 0 )
		YY_FATAL_ERROR( "start-condition stack underflow" );

	BEGIN(yy_start_stack[yy_start_stack_ptr]);
	}
#endif


#ifndef YY_NO_TOP_STATE
static int yy_top_state()
	{
	return yy_start_stack[yy_start_stack_ptr - 1];
	}
#endif

#ifndef YY_EXIT_FAILURE
#define YY_EXIT_FAILURE 2
#endif

#ifdef YY_USE_PROTOS
static void yy_fatal_error( yyconst char msg[] )
#else
static void yy_fatal_error( msg )
char msg[];
#endif
	{
	(void) fprintf( stderr, "%s\n", msg );
	exit( YY_EXIT_FAILURE );
	}



/* Redefine yyless() so it works in section 3 code. */

#undef yyless
#define yyless(n) \
	do \
		{ \
		/* Undo effects of setting up yytext. */ \
		yytext[yyleng] = yy_hold_char; \
		yy_c_buf_p = yytext + n; \
		yy_hold_char = *yy_c_buf_p; \
		*yy_c_buf_p = '\0'; \
		yyleng = n; \
		} \
	while ( 0 )


/* Internal utility routines. */

#ifndef yytext_ptr
#ifdef YY_USE_PROTOS
static void yy_flex_strncpy( char *s1, yyconst char *s2, int n )
#else
static void yy_flex_strncpy( s1, s2, n )
char *s1;
yyconst char *s2;
int n;
#endif
	{
	register int i;
	for ( i = 0; i < n; ++i )
		s1[i] = s2[i];
	}
#endif

#ifdef YY_NEED_STRLEN
#ifdef YY_USE_PROTOS
static int yy_flex_strlen( yyconst char *s )
#else
static int yy_flex_strlen( s )
yyconst char *s;
#endif
	{
	register int n;
	for ( n = 0; s[n]; ++n )
		;

	return n;
	}
#endif


#ifdef YY_USE_PROTOS
static void *yy_flex_alloc( yy_size_t size )
#else
static void *yy_flex_alloc( size )
yy_size_t size;
#endif
	{
	return (void *) malloc( size );
	}

#ifdef YY_USE_PROTOS
static void *yy_flex_realloc( void *ptr, yy_size_t size )
#else
static void *yy_flex_realloc( ptr, size )
void *ptr;
yy_size_t size;
#endif
	{
	/* The cast to (char *) in the following accommodates both
	 * implementations that use char* generic pointers, and those
	 * that use void* generic pointers.  It works with the latter
	 * because both ANSI C and C++ allow castless assignment from
	 * any pointer type to void*, and deal with argument conversions
	 * as though doing an assignment.
	 */
	return (void *) realloc( (char *) ptr, size );
	}

#ifdef YY_USE_PROTOS
static void yy_flex_free( void *ptr )
#else
static void yy_flex_free( ptr )
void *ptr;
#endif
	{
	free( ptr );
	}

#if YY_MAIN
int main()
	{
	yylex();
	return 0;
	}
#endif
#line 285 "ncgen.l"
